
sheets:
  expense_sheet: "1UdQszqnFgFJvkFmntiWG8Primz43dQkvEBU9IKV0fF0"
  expense_sheet_worksheet_name: "expenses"
  sheet_scope:
    - https://www.googleapis.com/auth/spreadsheets
    - https://www.googleapis.com/auth/drive

  taxonomy_sheet_id: "1YLVz3i6R9sYXW3oWfUEtFTMkrXyY6ONB4FohhTf4B8w"
  taxonomy_worksheet_name: "taxonomy"

paths:
  image_store: "data/images"

llm:
  embedding_model: "all-MiniLM-L6-v2"
  classification_model: "gpt-4.1"
  temperature: 0.0

# FAISS / Taxonomy
taxonomy:
    taxonomy_k: 5


logging:
  log_dir: "logs"
  level: "INFO"
